# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: self-hosted

    steps:
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
           path: ${{ github.workspace }}
           fail-build: true
           acs-report-enable: true
